# Auto-generated from final_exemptions.csv. Review and adjust values as needed.
tax_exemptions_records = [
    {
        "jurisdiction": ['Albania'],
        "ipcc": [],
        "fuel": ['Natural gas', 'Oil'],
        "year_from": 2024,
        "year_to": 2024,
        "value": None,
        "source": 'No. 9975',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Alberta'],
        "ipcc": [],
        "fuel": ['Natural gas', 'Oil'],
        "year_from": 2017,
        "year_to": 2019,
        "value": None,
        "source": 'Climate Leadership Act (C-16.9)',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Alberta'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2017,
        "year_to": 2019,
        "value": None,
        "source": 'Climate Leadership Act (C-16.9)',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Prince Edward Island'],
        "ipcc": [],
        "fuel": ['Natural gas', 'Oil'],
        "year_from": 2023,
        "year_to": 2023,
        "value": None,
        "source": 'GTN:309 / CLN:121 (May 2022)',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Spain'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2014,
        "year_to": 2015,
        "value": None,
        "source": 'BOE-A-2013-11331',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Estonia'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2024,
        "year_to": 2024,
        "value": None,
        "source": 'NA',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Ireland'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2024,
        "year_to": 2024,
        "value": None,
        "source": 'Revenue NGCT Manual',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Japan'],
        "ipcc": [],
        "fuel": ['Oil'],
        "year_from": 2012,
        "year_to": 2012,
        "value": None,
        "source": 'MOE Details on the Carbon Tax',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Japan'],
        "ipcc": [],
        "fuel": ['Coal'],
        "year_from": 2012,
        "year_to": 2012,
        "value": None,
        "source": 'MOE Details on the Carbon Tax',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Yucatan'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2022,
        "year_to": 2022,
        "value": None,
        "source": 'D.O. 30-12-2021 (adds Ch. XI)',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Norway'],
        "ipcc": [],
        "fuel": ['Oil'],
        "year_from": 2002,
        "year_to": 2002,
        "value": None,
        "source": 'Skatteetaten guidance',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Norway'],
        "ipcc": [],
        "fuel": ['Natural gas', 'Oil'],
        "year_from": 2002,
        "year_to": 2002,
        "value": None,
        "source": 'FOR-2001-12-11-1451',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Singapore'],
        "ipcc": [],
        "fuel": ['Natural gas'],
        "year_from": 2019,
        "year_to": 2019,
        "value": None,
        "source": 'Act 26 of 2018',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Slovenia'],
        "ipcc": ['1A3A'],
        "fuel": [],
        "year_from": 1996,
        "year_to": 1996,
        "value": None,
        "source": 'UL RS 68/1996',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
    {
        "jurisdiction": ['Slovenia'],
        "ipcc": ['1A3D'],
        "fuel": [],
        "year_from": 1996,
        "year_to": 1996,
        "value": None,
        "source": 'UL RS 68/1996',
        "notes": 'from final_exemptions.csv; inference=no_percent_found',
    },
]
