#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 15 17:36:50 2022

@author: gd
"""

# WCPD jurisdictions


## Countries

ctries = ['Afghanistan',
         'Albania',
         'Algeria',
         'Andorra',
         'Angola',
         'Antigua and Barbuda',
         'Argentina',
         'Armenia',
         'Australia',
         'Austria',
         'Azerbaijan',
         'Bahamas, The',
         'Bahrain',
         'Bangladesh',
         'Barbados',
         'Belarus',
         'Belgium',
         'Belize',
         'Benin',
         'Bhutan',
         'Bolivia',
         'Bosnia and Herzegovina',
         'Botswana',
         'Brazil',
         'Brunei Darussalam',
         'Bulgaria',
         'Burkina Faso',
         'Burundi',
         'Cabo Verde',
         'Cambodia',
         'Cameroon',
         'Canada',
         'Central African Republic',
         'Chad',
         'Chile',
         'China',
         'Colombia',
         'Comoros',
         'Congo, Dem. Rep.',
         'Congo, Rep.',
         'Costa Rica',
         "Cote d'Ivoire",
         'Croatia',
         'Cuba',
         'Cyprus',
         'Czech Republic',
         'Denmark',
         'Djibouti',
         'Dominica',
         'Dominican Republic',
         'Ecuador',
         'Egypt, Arab Rep.',
         'El Salvador',
         'Equatorial Guinea',
         'Eritrea',
         'Estonia',
         'Ethiopia',
         'Federated States of Micronesia',
         'Fiji',
         'Finland',
         'France',
         'Gabon',
         'Gambia, The',
         'Georgia',
         'Germany',
         'Ghana',
         'Greece',
         'Grenada',
         'Guatemala',
         'Guinea',
         'Guinea-Bissau',
         'Guyana',
         'Haiti',
         'Honduras',
         'Hong Kong SAR, China',
         'Hungary',
         'Iceland',
         'India',
         'Indonesia',
         'Iran, Islamic Rep.',
         'Iraq',
         'Ireland',
         'Israel',
         'Italy',
         'Jamaica',
         'Japan',
         'Jordan',
         'Kazakhstan',
         'Kenya',
         'Kiribati',
         'Korea, Dem. Rep.',
         'Korea, Rep.',
         'Kosovo',
         'Kuwait',
         'Kyrgyz Republic',
         'Lao PDR',
         'Latvia',
         'Lebanon',
         'Lesotho',
         'Liberia',
         'Libya',
         'Liechtenstein',
         'Lithuania',
         'Luxembourg',
         'Macao SAR, China',
         'Madagascar',
         'Malawi',
         'Malaysia',
         'Maldives',
         'Mali',
         'Malta',
         'Marshall Islands',
         'Mauritania',
         'Mauritius',
         'Mexico',
         'Moldova',
         'Monaco',
         'Mongolia',
         'Montenegro',
         'Morocco',
         'Mozambique',
         'Myanmar',
         'Namibia',
         'Nauru',
         'Nepal',
         'Netherlands',
         'New Zealand',
         'Nicaragua',
         'Niger',
         'Nigeria',
         'North Macedonia',
         'Norway',
         'Oman',
         'Pakistan',
         'Palau',
         'Panama',
         'Papua New Guinea',
         'Paraguay',
         'Peru',
         'Philippines',
         'Poland',
         'Portugal',
         'Puerto Rico',
         'Qatar',
         'Romania',
         'Russian Federation',
         'Rwanda',
         'Samoa',
         'San Marino',
         'Sao Tome and Principe',
         'Saudi Arabia',
         'Senegal',
         'Serbia',
         'Seychelles',
         'Sierra Leone',
         'Singapore',
         'Slovak Republic',
         'Slovenia',
         'Solomon Islands',
         'Somalia',
         'South Africa',
         'South Sudan',
         'Spain',
         'Sri Lanka',
         'St. Kitts and Nevis',
         'St. Lucia',
         'St. Vincent and the Grenadines',
         'Sudan',
         'Suriname',
         'Swaziland',
         'Sweden',
         'Switzerland',
         'Syrian Arab Republic',
         'Taiwan, China',
         'Tajikistan',
         'Tanzania',
         'Thailand',
         'Timor-Leste',
         'Togo',
         'Tonga',
         'Trinidad and Tobago',
         'Tunisia',
         'Turkey',
         'Turkmenistan',
         'Tuvalu',
         'Uganda',
         'Ukraine',
         'United Arab Emirates',
         'United Kingdom',
         'United States',
         'Uruguay',
         'Uzbekistan',
         'Vanuatu',
         'Vatican City',
         'Venezuela, RB',
         'Vietnam',
         'West Bank and Gaza',
         'Western Sahara',
         'Yemen, Rep.',
         'Zambia',
         'Zimbabwe']

## Subnational jurisdictions

### Canada

subnat_can = ['Alberta',
             'British Columbia',
             'Manitoba',
             'New Brunswick',
             'Newfoundland and Labrador',
             'Northwest Territories',
             'Nova Scotia',
             'Nunavut',
             'Ontario',
             'Prince Edward Island',
             'Quebec',
             'Saskatchewan',
             'Yukon']

### China

subnat_chn = ['Anhui Province',
             'Beijing Municipality',
             'Chongqing Municipality',
             'Fujian Province',
             'Gansu Province',
             'Guangdong Province',
             'Guangxi Zhuang Autonomous Region',
             'Guizhou Province',
             'Hainan Province',
             'Hebei Province',
             'Heilongjiang Province',
             'Henan Province',
             'Hong Kong Special Administrative Region',
             'Hubei Province',
             'Hunan Province',
             'Inner Mongolia Autonomous Region',
             'Jiangsu Province',
             'Jiangxi Province',
             'Jilin Province',
             'Liaoning Province',
             'Macau Special Administrative Region',
             'Ningxia Hui Autonomous Region',
             'Qinghai Province',
             'Shaanxi Province',
             'Shandong Province',
             'Shanghai Municipality',
             'Shanxi Province',
             'Shenzhen',
             'Sichuan Province',
             'Tianjin Municipality',
             'Tibet Autonomous Region',
             'Xinjiang Uyghur Autonomous Region',
             'Yunnan Province',
             'Zhejiang Province']

### Japan

subnat_jpn = ["Aichi",
              "Akita",
              "Aomori",
              "Chiba",
              "Ehime",
              "Fukui",
              "Fukuoka",
              "Fukushima",
              "Gifu",
              "Gunma",
              "Hiroshima",
              "Hokkaido",
              "Hyogo",
              "Ibaraki",
              "Ishikawa",
              "Iwate",
              "Kagawa",
              "Kagoshima",
              "Kanagawa",
              "Kochi",
              "Kumamoto",
              "Kyoto",
              "Mie",
              "Miyagi",
              "Miyazaki",
              "Nagano",
              "Nagasaki",
              "Nara",
              "Niigata",
              "Oita",
              "Okayama",
              "Okinawa",
              "Osaka",
              "Saga",
              "Saitama",
              "Shiga",
              "Shimane",
              "Shizuoka",
              "Tochigi",
              "Tokushima",
              "Tokyo",
              "Tottori",
              "Toyama",
              "Wakayama",
              "Yamagata",
              "Yamaguchi",
              "Yamanashi"]

### United States

subnat_usa = ['Alabama',
             'Alaska',
             'Arizona',
             'Arkansas',
             'California',
             'Colorado',
             'Connecticut',
             'Delaware',
             'Florida',
             'Georgia State',
             'Hawaii',
             'Idaho',
             'Illinois',
             'Indiana',
             'Iowa',
             'Kansas',
             'Kentucky',
             'Louisiana',
             'Maine',
             'Maryland',
             'Massachusetts',
             'Michigan',
             'Minnesota',
             'Mississippi',
             'Missouri',
             'Montana',
             'Nebraska',
             'Nevada',
             'New Hampshire',
             'New Jersey',
             'New Mexico',
             'New York',
             'North Carolina',
             'North Dakota',
             'Ohio',
             'Oklahoma',
             'Oregon',
             'Pennsylvania',
             'Rhode Island',
             'South Carolina',
             'South Dakota',
             'Tennessee',
             'Texas',
             'Utah',
             'Vermont',
             'Virginia',
             'Washington',
             'West Virginia',
             'Wisconsin',
             'Wyoming']

### Mexico

subnat_mex = ["Aguascalientes",
                "Baja California",
                "Baja California Sur",
                "Campeche",
                "Chiapas",
                "Chihuahua",
                "Coahuila de Zaragoza",
                "Colima",
                "Durango",
                "Guanajuato",
                "Guerrero",
                "Hidalgo",
                "Jalisco",
                "Mexico State",
                "Ciudad de Mexico",
                "Michoacan de Ocampo",
                "Morelos",
                "Nayarit",
                "Nuevo Leon",
                "Oaxaca",
                "Puebla",
                "Queretaro de Arteaga",
                "Quintana Roo",
                "San Luis Potosi",
                "Sinaloa",
                "Sonora",
                "Tabasco",
                "Tamaulipas",
                "Tlaxcala",
                "Veracruz de Ignacio de la Llave",
                "Yucatan"]


